version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    env_file:
      - ./frontend/.env  

  backend:
    build: ./backend
    ports:
      - "5100:5100"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=production
    env_file:
      - ./backend/.env  

networks:
  default:
    driver: bridge
